-- ============================================================================
-- Renumera o Campo de Ideias a partir de 1, na ordem de registro.
--
-- O `numero` é o ID que aparece na tela ("#26"). Ele saiu torto porque a
-- sequência da identity conta INSERTs, não linhas: o dado de demonstração que
-- foi apagado, as tentativas de carga e a importação da planilha consumiram
-- números que nunca chegaram a existir para o usuário. O painel abria em #26
-- com dez registros na tela.
--
-- A ordem é a de `criado_em` — a mesma da coluna "Registro" no mapa —, com o
-- id como desempate para o resultado não depender da ordem física da tabela.
--
-- ATENÇÃO: os números MUDAM. Quem tiver um "#31" anotado (e-mail de mudança de
-- status, print, conversa) passa a apontar para outro registro. Vale porque o
-- programa é novo e a numeração ainda não circulou.
--
-- A identity é GENERATED ALWAYS, que recusa UPDATE direto; por isso ela é
-- afrouxada para BY DEFAULT durante a correção e devolvida ao fim, com a
-- sequência reiniciada no próximo número livre.
-- ============================================================================

begin;

alter table public.programas_ideias alter column numero set generated by default;

with ordem as (
  select id, row_number() over (order by criado_em, id) as n
  from public.programas_ideias
)
update public.programas_ideias i
   set numero = ordem.n
  from ordem
 where ordem.id = i.id;

alter table public.programas_ideias alter column numero set generated always;

-- A sequência precisa continuar de onde a renumeração parou, senão o próximo
-- registro nasce repetindo um número que já está na tela.
do $$
declare proximo bigint;
begin
  select coalesce(max(numero), 0) + 1 into proximo from public.programas_ideias;
  execute format(
    'alter table public.programas_ideias alter column numero restart with %s', proximo
  );
end $$;

commit;
