-- Carga gerada por docs/gerar_carga_colaboradores.cjs
-- NAO editar a mao; regenerar a partir da planilha.
begin;

-- 1) Inserir colaboradores novos (socio/PJ/CNPJ)
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('ALESSANDRO PEREIRA MOREIRA', 'alessandro.moreira@phdengenharia.eng.br', 'COORDENADOR DE PLANEJAMENTOS', '2026-01-05', '1986-06-24', 'Sócio Cotista', 'gestor', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('MATHEUS AUGUSTO BRAGA DE MORAIS', 'matheus.morais@phdengenharia.eng.br', 'CONSULTOR DE PLANEJAMENTO', '2026-02-02', '2002-07-31', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('MYLENA ALVES ZOQBI', 'mylena.zoqbi@phdengenharia.eng.br', null, '2026-03-03', '1996-12-18', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('FELIPE GABRIEL COSTANZI', 'felipe.costanzi@phdengenharia.eng.br', 'CONSULTOR DE GESTÃO E PLANEJAMENTO', '2026-03-09', '1995-01-27', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('FERNANDO MUNIZ DE MENEZES', 'fernando.menezes@phdengenharia.eng.br', null, '2026-03-16', '1981-09-18', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('JOAO VICTOR SILVA MANGAS CATARINO', 'joao.catarino@phdengenharia.eng.br', null, '2026-05-04', '1994-06-03', 'Sócio Cotista', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('WANDERSON MATHEUS SILVA', 'wanderson.silva@phdengenharia.eng.br', null, '2026-05-04', '1995-08-01', 'Sócio Cotista', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('IGOR SILVA GUILHERME', 'igor.guilherme@phdengenharia.eng.br', null, '2026-05-04', '1997-09-08', 'Sócio Cotista', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('YITALON APARECIDO MIRANDA DE BRITO', 'yitalon.brito@phdengenharia.eng.br', null, '2026-05-18', '1997-11-30', 'Sócio Cotista', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('ALEXANDRE MOREIRA', 'alexandre.moreira@phdengenharia.eng.br', null, '2026-05-18', '1979-10-11', 'Sócio Cotista', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('RYAN MORAIS ARRAIS', 'ryan.arrais@phdengenharia.eng.br', null, '2026-06-01', '1993-01-29', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('MARCOS GREY SOARES CHAVES', 'marcos.chaves@phdengenharia.eng.br', null, '2026-06-01', '1975-12-24', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('RAMON MARTINS MEDEIROS', 'ramon.medeiros@phdengenharia.eng.br', null, '2026-06-01', '1987-09-20', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('ANDRE LUIZ DE CAMPOS', 'andre.campos@phdengenharia.eng.br', null, '2026-06-01', '1982-06-18', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('MICHEL CRUZ DOS SANTOS', 'michel.santos@phdengenharia.eng.br', null, '2026-06-01', '1982-03-05', 'PJ', 'usuario', true) on conflict (email) do nothing;
insert into colaboradores (nome, email, funcao, data_admissao, data_nascimento, formato, perfil, ativo) values ('CARLOS HENRIQUE PIMENTA DE VASCONCELOS', 'carlos.vasconcelos@phdengenharia.eng.br', null, '2026-06-01', '1979-01-10', 'PJ', 'usuario', true) on conflict (email) do nothing;

-- 2) Preencher formato em todos
update colaboradores set formato = 'CLT' where lower(email) = 'adailton.andrade@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'alessandra.sobral@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'aline.lage@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'alinne.oliveira@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'anaclaudia.costa@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'ana.caldeira@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'andre.gomes@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'andre.guimaraes@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'andrey.sousa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'angela.campos@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'arthur.andrade@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'artur.januth@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'brendo.lopes@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'bruno.azevedo@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'daniel.carlos@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'daniel.almeida@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'daniel.sousa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'deividy.gomes@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'diany.santana@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'diego.bernardes@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'diego.rodrigues@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'diogo.soares@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'edijane.rodrigues@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'eduardo.eler@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'eduardo.ferreira@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'fabio.oliveira@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'felipe.siqueira@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'fernando.silva@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'filiphe.santos@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'francisco.junior@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'gabriel.abud@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'getulio.pedrosa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'giovanna.braga@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'guilherme.silva@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'gustavo.marques@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'gustavo.lana@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'gutemberg.silva@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'hudson.vilela@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'icaro.bahia@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'isac.horta@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'ivan.silva@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'ivano.cruz@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'jader.correa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'jakeline.felix@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'jarbas.junior@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'jeferson.expedito@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'jefferson.magalhaes@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'jose.vargas@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'julio.cesar@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'karine.vitoria@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'lennon.santos@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'leonardo.drumond@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'leticia.nascimento@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'lucas.batista@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'lucas.assis@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'lucas.ferraz@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'lucas.zacarias@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'luiz.lopes@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'luiz.fernandes@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'maicon.morais@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'marcelo.lima@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'marcio.junior@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'marcos.ferrais@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'marlene.mozer@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'marlon.mueller@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'mateus.corradi@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'mateus.cerejo@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'matheus.dias@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'matheus.costa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'milena.neves@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'nilton.netto@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'paulo.paiva@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'paulohenrique.costa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'paulo.anastacio@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'paulo.junior@phdengenharia.eng.br';
update colaboradores set formato = 'Diretoria' where lower(email) = 'pedro.nery@phdengenharia.eng.br';
update colaboradores set formato = 'Diretoria' where lower(email) = 'pedro.morais@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'pedro.filho@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'pietro.rosa@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'polyane.lanes@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'rhavi.soares@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'roberto.medeiros@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'rodolpho.fonseca@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'rodrigo.brandolt@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'rodrigo.teixeira@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'ronaldo.machado@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'rosilaine.vaz@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'silas.moreira@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'talles.goncalves@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'tamiris.machado@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'thales.padua@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'tulio.rafael@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'victor.aguiar@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'victor.mota@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'vinicius.costa@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'wantuil.oliveira@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'yan.silva@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'yan.moreira@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'laura.sampaio@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'emerson.silva@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'pedro.chaves@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'roney.silva@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'fabio.santos@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'fernanda.ligorio@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'thais.oliveira@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'mateus.souza@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'divino.santos@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'washington.maciel@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'arthur.benedito@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'rafael.florencio@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'mariana.silva@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'raykleison.costa@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'diego.antunes@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'tainara.rodrigues@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'matheus.pera@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'alexander.rodrigues@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'thiago.letro@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'warley.campos@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'alessandro.moreira@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'daniela.sebrian@phdengenharia.eng.br';
update colaboradores set formato = 'CLT' where lower(email) = 'mauricio.silva@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'matheus.morais@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'mylena.zoqbi@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'felipe.costanzi@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'fernando.menezes@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'joao.catarino@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'wanderson.silva@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'igor.guilherme@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'yitalon.brito@phdengenharia.eng.br';
update colaboradores set formato = 'Sócio Cotista' where lower(email) = 'alexandre.moreira@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'ryan.arrais@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'marcos.chaves@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'ramon.medeiros@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'andre.campos@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'michel.santos@phdengenharia.eng.br';
update colaboradores set formato = 'PJ' where lower(email) = 'carlos.vasconcelos@phdengenharia.eng.br';

-- 3) Promover COO que nao sao gestores
update colaboradores set perfil = 'gestor' where lower(email) = 'alex.silva@phdengenharia.eng.br';
update colaboradores set perfil = 'gestor' where lower(email) = 'gabriel.abud@phdengenharia.eng.br';
update colaboradores set perfil = 'gestor' where lower(email) = 'nilton.netto@phdengenharia.eng.br';

-- 4) Definir superior_id (COO PHD)
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'jarbas.junior@phdengenharia.eng.br') where lower(email) = 'alessandra.sobral@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'mateus.corradi@phdengenharia.eng.br') where lower(email) = 'alinne.oliveira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'luciana.ferreira@phdengenharia.eng.br') where lower(email) = 'anaclaudia.costa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'daniel.almeida@phdengenharia.eng.br') where lower(email) = 'andre.gomes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'andre.guimaraes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'angela.campos@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'alex.silva@phdengenharia.eng.br') where lower(email) = 'artur.januth@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'brendo.lopes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'bruno.azevedo@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'alessandro.moreira@phdengenharia.eng.br') where lower(email) = 'daniel.carlos@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'daniel.almeida@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'daniel.sousa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'gabriel.abud@phdengenharia.eng.br') where lower(email) = 'deividy.gomes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'diego.bernardes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'diego.rodrigues@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'jarbas.junior@phdengenharia.eng.br') where lower(email) = 'edijane.rodrigues@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'eduardo.eler@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'eduardo.ferreira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'fabio.oliveira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'jarbas.junior@phdengenharia.eng.br') where lower(email) = 'felipe.siqueira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ana.caldeira@phdengenharia.eng.br') where lower(email) = 'fernando.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'filiphe.santos@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'tulio.rafael@phdengenharia.eng.br') where lower(email) = 'getulio.pedrosa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'giovanna.braga@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'eduardo.eler@phdengenharia.eng.br') where lower(email) = 'gustavo.lana@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'gutemberg.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'hudson.vilela@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'icaro.bahia@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'bruno.azevedo@phdengenharia.eng.br') where lower(email) = 'isac.horta@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'ivan.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'jader.correa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'jarbas.junior@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'jeferson.expedito@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'alessandro.moreira@phdengenharia.eng.br') where lower(email) = 'jefferson.magalhaes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'karine.vitoria@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'andre.guimaraes@phdengenharia.eng.br') where lower(email) = 'lennon.santos@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'mateus.corradi@phdengenharia.eng.br') where lower(email) = 'leticia.nascimento@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'lucas.batista@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'lucas.ferraz@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'tulio.rafael@phdengenharia.eng.br') where lower(email) = 'lucas.zacarias@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'luiz.fernandes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'luciana.ferreira@phdengenharia.eng.br') where lower(email) = 'maicon.morais@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'marcelo.lima@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'paulo.paiva@phdengenharia.eng.br') where lower(email) = 'marcos.ferrais@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'jarbas.junior@phdengenharia.eng.br') where lower(email) = 'marlene.mozer@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.morais@phdengenharia.eng.br') where lower(email) = 'mateus.corradi@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'matheus.dias@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'paulo.paiva@phdengenharia.eng.br') where lower(email) = 'nilton.netto@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'paulohenrique.costa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'paulo.anastacio@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'paulo.junior@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.nery@phdengenharia.eng.br') where lower(email) = 'pedro.morais@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'pietro.rosa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'polyane.lanes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'rhavi.soares@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'roberto.medeiros@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'tulio.rafael@phdengenharia.eng.br') where lower(email) = 'rodolpho.fonseca@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'bruno.azevedo@phdengenharia.eng.br') where lower(email) = 'ronaldo.machado@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'tulio.rafael@phdengenharia.eng.br') where lower(email) = 'silas.moreira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'tulio.rafael@phdengenharia.eng.br') where lower(email) = 'talles.goncalves@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'luciana.ferreira@phdengenharia.eng.br') where lower(email) = 'tamiris.machado@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'eduardo.eler@phdengenharia.eng.br') where lower(email) = 'thales.padua@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'gabriel.abud@phdengenharia.eng.br') where lower(email) = 'victor.aguiar@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'victor.mota@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'paulo.paiva@phdengenharia.eng.br') where lower(email) = 'wantuil.oliveira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'yan.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'yan.moreira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'alessandro.moreira@phdengenharia.eng.br') where lower(email) = 'emerson.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'paulo.paiva@phdengenharia.eng.br') where lower(email) = 'pedro.chaves@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'roney.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'fernanda.ligorio@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ana.caldeira@phdengenharia.eng.br') where lower(email) = 'thais.oliveira@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'tulio.rafael@phdengenharia.eng.br') where lower(email) = 'mateus.souza@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'divino.santos@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'luciana.ferreira@phdengenharia.eng.br') where lower(email) = 'washington.maciel@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'paulo.paiva@phdengenharia.eng.br') where lower(email) = 'arthur.benedito@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'rafael.florencio@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diego.bernardes@phdengenharia.eng.br') where lower(email) = 'raykleison.costa@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'tainara.rodrigues@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'alexander.rodrigues@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'julio.cesar@phdengenharia.eng.br') where lower(email) = 'warley.campos@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'pedro.nery@phdengenharia.eng.br') where lower(email) = 'daniela.sebrian@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'jarbas.junior@phdengenharia.eng.br') where lower(email) = 'mauricio.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'ronaldo.machado@phdengenharia.eng.br') where lower(email) = 'matheus.morais@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'daniel.almeida@phdengenharia.eng.br') where lower(email) = 'mylena.zoqbi@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'felipe.costanzi@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'diogo.soares@phdengenharia.eng.br') where lower(email) = 'fernando.menezes@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'nilton.netto@phdengenharia.eng.br') where lower(email) = 'wanderson.silva@phdengenharia.eng.br';
update colaboradores set superior_id = (select id from colaboradores where lower(email) = 'thales.padua@phdengenharia.eng.br') where lower(email) = 'ryan.arrais@phdengenharia.eng.br';

commit;